### ISSUE TITLE
Alignment between garment and clothing

### ISSUE THREAD

**Issue by sunshineatnoon** [sail-sg/sewformer#10]
Hi, Thanks for open-sourcing this awesome work. 

I tried to "dress" a SMPLH mesh with the clothing from the SewFactory dataset. Specifically, I use `fbx_anime.py` to produce a SMPLH body with the pose parameter from `static__body_info.json` in the dataset. Then I visualize the produced SMPLH body and the clothing (e.g., `skirt_8_panels_SFQLFR9GJI_skirt_8_panels_SFQLFR9GJI.obj` from the `tee_1A4AUUJT75_skirt_8_panels_SFQLFR9GJI/static` folder) side by side, but it seems they are not aligned (shown below). Is there anything I'm missing here? I suspect there is also a translation for the clothing, if so, where can I find it? Thanks!
<img width="287" alt="Screen Shot 2024-01-19 at 2 02 49 PM" src="https://github.com/sail-sg/sewformer/assets/7546747/a97c6cfe-7ff9-4268-bb9f-bc0a5c08f4af">

**Comment by boyang-yu** [comment]
Hi,

Did you figure out why there is such displacement? I just have the same problem here. 
Besides, when I try to use the pose parameters in the "0000_body_info.json" located in the "poses" folder(e.g.  tee_ZZHFVSA17Q_pants_straight_sides_ULX5THI3A5), it does not even return a valid SMPL-H body mesh...

**Comment by boyang-yu** [comment]
![twisted](https://github.com/sail-sg/sewformer/assets/37520512/1ef5aab1-8c70-4538-aef0-102251617382)

**Comment by SMY19999** [comment]
For the alignment, I just find some code in dataloader, it seems that in /static/spec_config.json, delta is the translation. 
In code, data/dataset.py 
`
def _load_spec_dict(): 
   spec_dict[key]['delta']=np.array(val("delta")) - np.array(static_root)
`
static_root is the translation of SMPL root joint.

**Comment by SMY19999** [comment]
Though I didn't do the experiment, I guess it is because the pose parameters are different between SMPL and SMPL-H. Just try using SMPL.
> Hi,
> 
> Did you figure out why there is such displacement? I just have the same problem here. Besides, when I try to use the pose parameters in the "0000_body_info.json" located in the "poses" folder(e.g. tee_ZZHFVSA17Q_pants_straight_sides_ULX5THI3A5), it does not even return a valid SMPL-H body mesh...
