### ISSUE TITLE
"customconfig" module

### ISSUE THREAD

**Issue by Yingqi7777** [sail-sg/sewformer#13]
Dear author,

Thanks for the code update. I have tried these three: training, evaluation on SewFactory or inference on DeepFashion, but got the same error: 

 "ModuleNotFoundError: No module named 'customconfig'". 

I see this module is written by yourself, and could you check if you upload the corresponding code? Thanks.

**Comment by Cao-Cong0** [comment]
> Dear author,
> 
> Thanks for the code update. I have tried these three: training, evaluation on SewFactory or inference on DeepFashion, but got the same error:
> 
> "ModuleNotFoundError: No module named 'customconfig'".
> 
> I see this module is written by yourself, and could you check if you upload the corresponding code? Thanks.

The module path is SewFactory/packages/customconfig.py
