### ISSUE TITLE
Where to download SMPLH_female_010_207.fbx?

### ISSUE THREAD

**Issue by sunshineatnoon** [sail-sg/sewformer#18]
Hi, I followed the instruction [here](https://github.com/sail-sg/sewformer/tree/main/SewFactory#configuration) to generate animated body pose sequence, but I cannot find the SMPLH_female_010_207.fbx from the given link in this page nor from the SMPLH website. Could you please point me to the correct location? Thanks!

**Comment by wqs111000** [comment]
Did you solve it? I have the same question. Could you please point me to the correct location? Thanks!
