### ISSUE TITLE
rpmaya plugin

### ISSUE THREAD

**Issue by Mamba-ZJP** [sail-sg/sewformer#2]
I meet a problem when I do simulation after panel prediction:
MTL file: meta_infos\scene_materials\materials.mb, namespace: imported_mtl
文件读取所用时间为  0.084 秒。
错误: line 1: RuntimeError: file <maya console> line 1: 在 MAYA_PLUG_IN_PATH 上找不到插件“rpmaya”。
MTL file: meta_infos\scene_materials\materials.mb, namespace: extra_mtl
文件读取所用时间为  0.01 秒。

So what is the"rpmaya" plugin? I searched it, but it seems not an official plugin of maya.

**Comment by Mamba-ZJP** [comment]
I am using Maya2020.4 and Qualoth.

**Comment by Mamba-ZJP** [comment]
It seems error happens when maya try to load material.mb file.

**Comment by LSQsjtu** [comment]
Have you solved this error？ I also met it when running deepfashion_sim.py to get the results.

**Comment by gjgjgjfff** [comment]
Have you solved this error？ I also met it when running deepfashion_sim.py to get the results.

**Comment by gjgjgjfff** [comment]
> I meet a problem when I do simulation after panel prediction: MTL file: meta_infos\scene_materials\materials.mb, namespace: imported_mtl 文件读取所用时间为 0.084 秒。 错误: line 1: RuntimeError: file line 1: 在 MAYA_PLUG_IN_PATH 上找不到插件“rpmaya”。 MTL file: meta_infos\scene_materials\materials.mb, namespace: extra_mtl 文件读取所用时间为 0.01 秒。
> 
> So what is the"rpmaya" plugin? I searched it, but it seems not an official plugin of maya.

Hi, Have you solved this error？ I also met it when running data_sim.py to get the 3D Mesh. Looking forward to your reply ！
