### ISSUE TITLE
Generation needs joints_mat_SMPLH.npz

### ISSUE THREAD

**Issue by Mamba-ZJP** [sail-sg/sewformer#4]
When I Generate posed smpl files with different pose sequences. `path_to_maya2020\bin\mayapy.exe .\data_generator\fbx_anime.py -o examples\\posed_fbxs,`
it reports error: `IOError: (2, 'No such file or directory', u'meta_i...MPLH.npz')`

It seems that configs writes it needs `meta_infos\\fbx_metas\\joints_mat_SMPLH.npz`.

**Comment by xyyeah** [comment]
Pls download it from this [link](https://github.com/Meshcapade/SMPL_maya_plugin/commit/e6d88e5dfcb9b24f2905e8dd92762fecb9a86370)

**Comment by Mamba-ZJP** [comment]
thanks

**Comment by 22036435** [comment]
File read in  16.1 seconds.
Error generating posed FBXs: 'in <string>' requires string as left operand, not list
Exception ignored in: <function MCallbackIdWrapper.__del__ at 0x0000026F7F4CF880>

after this file uploaded I started to get this error

**Comment by 22036435** [comment]
> File read in 16.1 seconds. Error generating posed FBXs: 'in ' requires string as left operand, not list Exception ignored in: <function MCallbackIdWrapper.**del** at 0x0000026F7F4CF880>
> 
> after this file uploaded I started to get this error

I think mainly it's about the poses.npz file.
Can you share me what exactly are using as poses.npz file?
