### ISSUE TITLE
TypeError: __init__() missing 1 required positional argument: 'start_config'

### ISSUE THREAD

**Issue by pasqualesimonetti** [sail-sg/sewformer#6]
```
$ python inference.py -c ./configs/test.yaml -d ./assets/data/deepfashion -t deepfashion -o outputs/deepfashion
C:\Developer/sewformer/SewFactory/packages
C:\Developer/sewformer/SewFactory/packages
ExperimentWrappper::Warning::Requested status of run not connected to wandb
ExperimentWrappper::Warning::Skipping loading split file from cloud..
ExperimentWrappper::Warning::Skipping loading panel classes file from cloud..
ExperimentWrappper::Warning::Skipping loading parameter filter file from cloud..
Traceback (most recent call last):
  File "C:\Developer\sewformer\Sewformer\inference.py", line 144, in <module>
    shape_dataset, shape_datawrapper = shape_experiment.load_detr_dataset(
  File "C:\Developer\sewformer\Sewformer\experiment.py", line 249, in load_detr_dataset
    dataset = data_class(data_root, data_config, gt_caching=True, feature_caching=False)
TypeError: __init__() missing 1 required positional argument: 'start_config'
```

**Comment by Mamba-ZJP** [comment]
In fact, you should manually add a argument called `sim_root` in `line 249, in load_detr_dataset`. Then you can go. 
I should remind that many bugs you met are the ones I met before. You can try and fix bug by yourself, as the code have many small bugs like two issues you proposed before.
We can discuss through emails. 
And good luck!

**Comment by TianZhenGG** [comment]
> In fact, you should manually add a argument called `sim_root` in `line 249, in load_detr_dataset`. Then you can go. I should remind that many bugs you met are the ones I met before. You can try and fix bug by yourself, as the code has many small bugs like two issues you proposed before. We can discuss through emails. And good luck!

can you give an example,thanks.

**Comment by Cimcum** [comment]
Did anyone resolve that issue?

**Comment by IHe-KaiI** [comment]
I tried to add ```start_config=data_config``` in ```line 249 \Sewformer\experiment.py file```, and it works.

**Comment by nagexiaochengzi** [comment]
AttributeError: 'str' object has no attribute 'update'.How did you solve this problem?

**Comment by pabloriosn** [comment]
I fixed this problem changing the line 249:

`dataset = data_class(data_root, sim_root= {}, start_config=data_config, gt_caching=True, feature_caching=False)`
