### ISSUE TITLE
TypeError: coercing to Unicode: need string or buffer, list found

### ISSUE THREAD

**Issue by ZishengYePhD** [sail-sg/sewformer#7]
The error is located in `self.body_fSMPL = [ch for ch in children if model_type in ch and 'rig' not in ch][0]`, in function `_collect_body_params` in `fbx_animation.py`.

This error occurs both in Sewformer readme - Testing - Step 2, i.e. `path_to_maya\bin\mayapy.exe .\data_generator\deepfashion_sim.py`, and SewFactory readme - Generation - Step 2, i.e. `path_to_maya2020\bin\mayapy.exe .\data_generator\fbx_anime.py -o examples\\posed_fbxs`. 

When I first met this issue in Sewformer readme - Testing - Step 2, I went through the code to locate the error. 
`Traceback (most recent call last):`
  `File ".\data_generator\deepfashion_sim.py", line 128, in <module>
    playblast.simulate_predictions(predictions, retrieve_props=args.dataname=="sewfactory", logger=logger)`
  `File ".\packages\mayaqltools\playblast.py", line 723, in simulate_predictions
    body_conf, smpl_shape = self.retieve_props(pred_folder, retrieve_props)`
  `File ".\packages\mayaqltools\playblast.py", line 698, in retieve_props
    self.body = fbx_animation.SmplBody(config=c_conf)`
  `File ".\packages\mayaqltools\fbx_animation.py", line 66, in __init__
    self.load_body()`
  `File ".\packages\mayaqltools\fbx_animation.py", line 91, in load_body
    cmds.file(self.body_file, i=True, type='Fbx', ignoreVersion=True, groupReference=True, groupName="bodyfbx")`
  `File ".\packages\mayaqltools\fbx_animation.py", line 109, in add_motion
    self._collect_body_params(bodyfbx)`
  `File ".\packages\mayaqltools\fbx_animation.py", line 518, in _collect_body_params
    self.body_fSMPL = [ch for ch in children if model_type in ch and 'rig' not in ch][0]`
`TypeError: coercing to Unicode: need string or buffer, list found`

It turns out that given an fbx file as base fbx, `load_body` in `fbx_animation.py` will iterate through all transforms available to find `bodyfbx`: `bodyfbx = [bf for bf in cmds.ls(transforms=True) if "bodyfbx" in bf][0]`. The selected `bodyfbx` is eventually passed into `add_motion` and `_collect_body_params` to collect SMPL-related parameters. 

In `_collect_body_params`, all children of selected `bodyfbx` are examined to determine which type of SMPL it is using. If its type is determined, `model_type = ['SMPLH', "SMPLX", "SMPL"]` will change to the specific category: 
`for mt in model_type:`
            `body_smpl = [ch for ch in children if mt in ch and 'rig' not in ch]`
            `if len(body_smpl) > 0:`
                `self.body_fSMPL = body_smpl[0]`
                `model_type = mt`
                `break`

However, there is **_no such children that can determine the SMPL type_**. Therefore, when `model_type` is passed into `self.body_fSMPL = [ch for ch in children if model_type in ch and 'rig' not in ch][0]`, type error occurs: `TypeError: coercing to Unicode: need string or buffer, list found`.

**Just wondering how can I solve such issue?** I've tried multiple solutions, such as **changing base fbx files** (`SMPL`, `SMPL-maya`, `SMPLH`), changing the commented line between `self.body_fSMPL` and `self.body_rig`. 

Thank you!

**Comment by ZishengYePhD** [comment]
specified fbx files in smpl-maya-plugin **GitHub Repo** are needed, not on SMPL official page.

**Comment by gjgjgjfff** [comment]
> specified fbx files in smpl-maya-plugin **GitHub Repo** are needed, not on SMPL official page.

Hello, I encountered the same problem, after using smpl-maya-plugin GitHub Repo, skeleton = cmds.listConnections(self._get_associated_deformer(bodyshape, 'skinCluster'), type='joint') gets None. How do you solve it？

**Comment by gjgjgjfff** [comment]
> specified fbx files in smpl-maya-plugin **GitHub Repo** are needed, not on SMPL official page.

Hello, I encountered the same problem, after using smpl-maya-plugin GitHub Repo, in function _collect_body_params in fbx_animation.py., line 522, skeleton = cmds.listConnections(self._get_associated_deformer(bodyshape, 'skinCluster'), type='joint') gets None. How do you solve it

**Comment by DDCAR123** [comment]
> specified fbx files in smpl-maya-plugin **GitHub Repo** are needed, not on SMPL official page.

When importing this FBX file, I encountered the following error: "The following parent and/or ancestor node of the Link(s) is/are not part of the BindPose definition: fSMPLH_rig."Could you have any solution for this?

**Comment by yatengLG** [comment]
> > specified fbx files in smpl-maya-plugin **GitHub Repo** are needed, not on SMPL official page.
> 
> Hello, I encountered the same problem, after using smpl-maya-plugin GitHub Repo, in function _collect_body_params in fbx_animation.py., line 522, skeleton = cmds.listConnections(self._get_associated_deformer(bodyshape, 'skinCluster'), type='joint') gets None. How do you solve it

Have you solved it? I also meet this problem ```skeleton and bodyshape are both None.```
